[_tb_system_call storage=system/_preview.ks ]

[mask time=10]
[bg  time="10"  method="crossfade"  storage="inakaminka.png"  ]
[tb_show_message_window] 
[mask_off time=10]
[tb_start_text mode=2 ]
パタンとアルバムを閉じて目を瞑る。[l][r]
[_tb_end_text]

[cm  ]
[tb_start_text mode=2 ]
「……もう何もできないけど、幸せにな」[l][r]
[_tb_end_text]

[cm  ]
[mask  time="1000"  effect="fadeIn"  color="0x000000"  ]
[bg  time="1000"  method="crossfade"  storage="black.png"  ]
[jump  storage="title_screen.ks"  target=""  ]
[s  ]
