[preload  storage="./data/bgimage/black.png"  ]
[preload  storage="./data/bgimage/late_park.jpg"  ]
[preload  storage="./data/fgimage/chara/2/ichihashi_1.png"  ]
[preload  storage="./data/bgimage/mansyon.jpg"  ]
[preload  storage="./data/bgimage/ima.jpg"  ]
[preload  storage="./data/bgimage/kyousitu.jpg"  ]
[preload  storage="./data/fgimage/chara/1/ueda_1.png"  ]
[preload  storage="./data/bgimage/rouka_.jpg"  ]
[preload  storage="./data/bgimage/kouen2.jpg"  ]
[return]